name: Automated Triage

on:
  issues:
    types:
      - opened
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  triage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Triage Issues
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            python .github/scripts/triage.py "${{ github.event.action }}" "${{ github.event.issue.number }}" "${{ github.event.issue.labels }}" "${{ secrets.GITHUB_TOKEN }}"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            python .github/scripts/triage.py "${{ github.event.action }}" "${{ github.event.pull_request.number }}" "${{ github.event.pull_request.labels }}" "${{ secrets.GITHUB_TOKEN }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
